### ISSUE TITLE
Port 445 not required on NC V14 or V15

### ISSUE THREAD

**Issue by Helkyd** [doloresjuliana/pibiapp#24]
Hi 
Had to make a correction on your code by removing the port 445
self.baseurl = '{0}://{1}'.format(protocol, host)

You should test to see if the NC requires that port or not...

**Comment by doloresjuliana** [comment]
It has been changed so that port 443 or 80 is not essential in the parameterization.

If the NextCloud version requires a port, it must be specified in the Script URL parameter.

https://github.com/doloresjuliana/pibiapp/commit/d308ce9d1513ae9a69cb4ce54d9c0bdb489f8712
