### ISSUE TITLE
Naming files problem

### ISSUE THREAD

**Issue by Helkyd** [doloresjuliana/pibiapp#25]
Also having some issues with file naming ... renamed from 
fname = frappe.db.get_value("File", {"file_name": ["like", doc.file_name + " NC/f/%"]}, "name")

to
fname = frappe.db.get_value("File", {"file_name": ["like", doc.file_name + "%"]}, "name")

Just give a test from your side to see... currently using Frappe v10.1.42 / ERpnext 10.1.43 will upgrade to last V10 soon and give a try again...

**Comment by doloresjuliana** [comment]
Changing NC/f/ to NC_f_ in previous versions did not cause problems, but a validation in Frappe's file.py prevents its use.

This app has been updated for Frappe V14. Although it was classified as DEPRECATED after the development in V12 of https://github.com/pibico/pibiDAV It is another integration with Nextcloud with similar functionality improved and expanded.
