### ISSUE TITLE
Connecting to my Nextcloud Server Problem

### ISSUE THREAD

**Issue by Helkyd** [doloresjuliana/pibiapp#26]
Hi,
On Settings the Server Path should check for Backslash \ as i entered the full path with it and was not connecting only after checking the Source i could see that the problem was with the \ being present on the Script URL

**Comment by doloresjuliana** [comment]
I'm not sure I understand, sorry. The parameterization should be like this:
Nextcloud Settings 
Script URL: https://mynextcloud.com
WebDav Path: /remote.php/dav/files/myusernextcloud/     Or what your NextCloud indicates in the WebDav information

Esta aplicación se ha actualizado para Frappe V14 but the parameterization must be done with "/"
