### ISSUE TITLE
Version 12 - No Features at all after installation

### ISSUE THREAD

**Issue by robertolanuti** [doloresjuliana/pibiapp#28]
Hi,

as mentioned in the post #27 even if the app is successfully installed on Version 12, I cannot see any menu/feature related to that (I have tried to search something related to the Nextcloud module without success). 

The only new thing that I can see related to the app is the Checkbox "Nextcloud" that is inside the  "ALLOW MODULES" tab in the User Form.

Any idea related to that?

Thanks and Regards,
Roberto

**Comment by AmauryVanEspen** [comment]
+1 to solve the issue

**Comment by pibico** [comment]
> 
> 
> Hi,
> 
> as mentioned in the post #27 even if the app is successfully installed on Version 12, I cannot see any menu/feature related to that (I have tried to search something related to the Nextcloud module without success).
> 
> The only new thing that I can see related to the app is the Checkbox "Nextcloud" that is inside the "ALLOW MODULES" tab in the User Form.
> 
> Any idea related to that?
> 
> Thanks and Regards,
> Roberto

You can correct the visibility, modifying the file desktop.py in folder config, and changing hidden: 1 to hidden: 0.

**Comment by doloresjuliana** [comment]
This app has been updated for Frappe V14. It includes the creation of a workspace dependent on the Frappe integrations and other necessary fixes.

Although it was classified as DEPRECATED after the development in V12 of https://github.com/pibico/pibiDAV
It is another integration with Nextcloud with similar functionality improved and expanded.
